service: lambda-consumer

provider:
  deploymentBucket: your-serverless-bucket
  iamRoleStatements:
  - Effect: Allow
    Action:
      - sqs:*
      # Refine policy
      # - sqs:DeleteMessage
      # - sqs:ReceiveMessage
    Resource: arn:
  name: aws
  profile: poc-delivery
  region: ap-southeast-1
  runtime: nodejs6.10
  stage: dev

functions:
  hello:
    handler: handler.consumer
    events:
      # Subscribe to SNS topic. Will call the receive message on lambda whenever an event is published to the topic.
      - sns:
          arn: arn:aws:xxx:xxx

# Create SQS and Dead Letter Queue
# resources:
#   Resources:
#     Messages:
#       Type: AWS::SQS::Queue
#       Properties:
#         QueueName: poc-delivery
#         MessageRetentionPeriod: 1209600
#         VisibilityTimeout: 60
#         RedrivePolicy:
#           deadLetterTargetArn:
#             Fn::GetAtt:
#             - MessagesDeadLetterQueue
#             - Arn
#           maxReceiveCount: 10

#     MessagesDeadLetterQueue:
#       Type: AWS::SQS::Queue
#       Properties:
#         QueueName: poc-delivery-dead-letter-queue
#         MessageRetentionPeriod: 1209600
